name: Deploy docs to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - packages/docs/**

  # Enables manual deployments from the Actions tab
  workflow_dispatch:

# Sets permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# Do NOT cancel in-progress runs to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/shared/setup-node"
      - run: pnpm --filter "markdoc-svelte-docs" build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/docs/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
