name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  test-svelte:
    runs-on: ubuntu-latest
    steps:
      - uses: "./.github/shared/setup-node"
      - name: Test
        run: pnpm test
      - name: Test build
        run: pnpm build
