name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  test-svelte:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: "./.github/shared/setup-node"
        # Build before test to get the SvelteKit files
      - name: Test build
        run: pnpm build
      - name: Test
        run: pnpm test
